import { PartyMember } from "../dndbeyond.types";
import { ABILITY_NAMES } from "./constants";

export function titleCase(s: string): string {
  return s.replace(/[-_]+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

export function errorMember(id: number, message: string): PartyMember {
  return {
    id,
    name: `Character ${id}`,
    avatarUrl: null,
    race: "—",
    background: "",
    classes: "—",
    subclasses: [],
    level: 0,
    hpMax: 0,
    hpCurrent: 0,
    tempHp: 0,
    inspiration: false,
    exhaustion: 0,
    deathSaves: { successes: 0, failures: 0, stabilized: false },
    passivePerception: 0,
    passiveInvestigation: 0,
    passiveInsight: 0,
    armorClass: 0,
    initiative: 0,
    speed: 0,
    proficiencyBonus: 0,
    senses: [],
    skills: [],
    saves: [],
    spellSlots: [],
    pactSlots: [],
    abilities: ABILITY_NAMES.map((name) => ({ name, score: 0, modifier: 0 })),
    conditions: [],
    defenses: [],
    actions: [],
    inventory: [],
    languages: [],
    tools: [],
    armorProficiencies: [],
    weaponProficiencies: [],
    specialSpeeds: [],
    spellcasting: [],
    hitDice: "—",
    feats: [],
    alignment: null,
    currencies: { cp: 0, sp: 0, ep: 0, gp: 0, pp: 0 },
    weightCarried: 0,
    carryingCapacity: 0,
    attacks: [],
    cantrips: [],
    preparedSpells: [],
    allSpells: [],
    features: [],
    characteristics: {
      personalityTraits: "",
      ideals: "",
      bonds: "",
      flaws: "",
      appearance: "",
      gender: "",
      age: "",
      height: "",
      weight: "",
      eyes: "",
      skin: "",
      hair: "",
      backstory: "",
      allies: "",
      enemies: "",
      organizations: "",
      otherNotes: "",
    },
    readonlyUrl: `https://www.dndbeyond.com/characters/${id}`,
    error: message,
    activeArmorModel: null,
    activeInfusions: [],
    infusions: [],
    metamagic: [],
    totemAspects: [],
    weaponMasteries: [],
    creatures: [],
  };
}
