export const SOURCE_LABELS: Record<string, string> = {
  AAG: "Astral Adventurer's Guide",
  AI: "Acquisitions Incorporated",
  BAM: "Boo's Astral Menagerie",
  BGG: "Bigby Presents: Glory of the Giants",
  BMT: "The Book of Many Things",
  XPHB: "Player's Handbook",
  XDMG: "Dungeon Master's Guide",
  XMM: "Monster Manual",
  FTD: "Fizban's Treasury of Dragons",
  TCE: "Tasha's Cauldron of Everything",
  XGE: "Xanathar's Guide to Everything",
  EFA: "Eberron: Forge of the Artificer",
  ERLW: "Eberron: Rising from the Last War",
  EGW: "Explorer's Guide to Wildemount",
  GGR: "Guildmasters' Guide to Ravnica",
  MOT: "Mythic Odysseys of Theros",
  MPMM: "Mordenkainen Presents: Monsters of the Multiverse",
  MTF: "Mordenkainen's Tome of Foes",
  MPP: "Morte's Planar Parade",
  FRAIF: "Forgotten Realms: Adventures in Faerun",
  FRHOF: "Forgotten Realms: Heroes of Faerun",
  RHW: "Ravenloft: The Horrors Within",
  SATO: "Sigil and the Outlands",
  SCAG: "Sword Coast Adventurer's Guide",
  SCC: "Strixhaven: A Curriculum of Chaos",
  VGM: "Volo's Guide to Monsters",
  VRGR: "Van Richten's Guide to Ravenloft",
};

export const ABILITIES = ["STR", "DEX", "CON", "INT", "WIS", "CHA"];
export const ABILITY_NAMES: Record<string, string> = {
  STR: "Strength",
  DEX: "Dexterity",
  CON: "Constitution",
  INT: "Intelligence",
  WIS: "Wisdom",
  CHA: "Charisma",
};

export const SKILL_OPTIONS = [
  "Acrobatics",
  "Animal Handling",
  "Arcana",
  "Athletics",
  "Deception",
  "History",
  "Insight",
  "Intimidation",
  "Investigation",
  "Medicine",
  "Nature",
  "Perception",
  "Performance",
  "Persuasion",
  "Religion",
  "Sleight of Hand",
  "Stealth",
  "Survival",
];

export const TOOL_OPTIONS = [
  "Alchemist's Supplies",
  "Brewer's Supplies",
  "Calligrapher's Supplies",
  "Carpenter's Tools",
  "Cartographer's Tools",
  "Cobbler's Tools",
  "Cook's Utensils",
  "Glassblower's Tools",
  "Jeweler's Tools",
  "Leatherworker's Tools",
  "Mason's Tools",
  "Painter's Supplies",
  "Potter's Tools",
  "Smith's Tools",
  "Thieves' Tools",
  "Tinker's Tools",
  "Weaver's Tools",
  "Woodcarver's Tools",
  "Disguise Kit",
  "Forgery Kit",
  "Herbalism Kit",
  "Navigator's Tools",
  "Poisoner's Kit",
];

export const FIGHTING_STYLE_OPTIONS = [
  "Archery",
  "Blind Fighting",
  "Defense",
  "Dueling",
  "Great Weapon Fighting",
  "Interception",
  "Protection",
  "Thrown Weapon Fighting",
  "Two-Weapon Fighting",
  "Unarmed Fighting",
];

export const WEAPON_MASTERY_OPTIONS = [
  "Battleaxe",
  "Club",
  "Dagger",
  "Dart",
  "Flail",
  "Glaive",
  "Greataxe",
  "Greatclub",
  "Greatsword",
  "Halberd",
  "Handaxe",
  "Javelin",
  "Lance",
  "Light Hammer",
  "Longbow",
  "Longsword",
  "Mace",
  "Maul",
  "Morningstar",
  "Pike",
  "Quarterstaff",
  "Rapier",
  "Scimitar",
  "Shortbow",
  "Shortsword",
  "Sickle",
  "Sling",
  "Spear",
  "Trident",
  "Warhammer",
  "Whip",
];

export const PREPARED_SPELLS_BY_CLASS: Record<string, number[]> = {
  artificer: [2, 3, 4, 5, 6, 6, 7, 7, 9, 10, 10, 11, 11, 12, 13, 13, 14, 14, 15, 15],
  bard: [4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 15, 16, 16, 17, 18, 18, 19, 20, 22, 22],
  cleric: [4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 15, 16, 16, 17, 18, 18, 19, 20, 22, 22],
  druid: [4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 15, 16, 16, 17, 18, 18, 19, 20, 22, 22],
  paladin: [0, 2, 3, 3, 5, 6, 6, 7, 7, 9, 10, 10, 11, 11, 12, 13, 13, 14, 14, 15],
  ranger: [0, 2, 3, 3, 5, 6, 6, 7, 7, 9, 10, 10, 11, 11, 12, 13, 13, 14, 14, 15],
  sorcerer: [4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 15, 16, 16, 17, 18, 18, 19, 20, 22, 22],
  warlock: [2, 3, 4, 5, 6, 7, 7, 8, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 15, 15],
  wizard: [4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 15, 16, 16, 17, 18, 18, 19, 20, 22, 22],
};

export const INVOCATION_LEVEL_PREREQUISITES: Record<string, number> = {
  "Ascendant Step": 5,
  "Devouring Blade": 12,
  Lifedrinker: 9,
  "Master of Myriad Forms": 5,
  "One with Shadows": 5,
  "Otherworldly Leap": 2,
  "Thirsting Blade": 5,
  "Visions of Distant Realms": 9,
  "Whispers of the Grave": 7,
  "Witch Sight": 15,
};

export const INVOCATION_PACT_PREREQUISITES: Record<string, string> = {
  "Devouring Blade": "Pact of the Blade",
  "Eldritch Smite": "Pact of the Blade",
  "Gift of the Protectors": "Pact of the Tome",
  "Investment of the Chain Master": "Pact of the Chain",
  Lifedrinker: "Pact of the Blade",
  "Thirsting Blade": "Pact of the Blade",
};

export const WARLOCK_INVOCATION_COUNTS = [
  1, 3, 3, 3, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 10, 10,
];

export const DRAGON_DAMAGE_BY_ANCESTRY: Record<string, string> = {
  Black: "Acid",
  Blue: "Lightning",
  Brass: "Fire",
  Bronze: "Lightning",
  Copper: "Acid",
  Gold: "Fire",
  Green: "Poison",
  Red: "Fire",
  Silver: "Cold",
  White: "Cold",
  Amethyst: "Force",
  Crystal: "Radiant",
  Emerald: "Psychic",
  Sapphire: "Thunder",
  Topaz: "Necrotic",
};

export type ClassTheme = {
  text: string;
  textMuted: string;
  bg: string;
  bgActive: string;
  border: string;
  borderFocus: string;
  ring: string;
  glow: string;
  glowBlur: string;
  primaryBtn: string;
};

export const CLASS_THEMES: Record<string, ClassTheme> = {
  barbarian: {
    text: "text-red-500",
    textMuted: "text-red-400",
    bg: "bg-red-500/10",
    bgActive: "bg-red-500/20",
    border: "border-red-500/30",
    borderFocus: "focus:border-red-500",
    ring: "focus:ring-red-500",
    glow: "from-red-950/20",
    glowBlur: "bg-red-500/15",
    primaryBtn: "bg-red-600 hover:bg-red-700 text-white",
  },
  bard: {
    text: "text-pink-500",
    textMuted: "text-pink-400",
    bg: "bg-pink-500/10",
    bgActive: "bg-pink-500/20",
    border: "border-pink-500/30",
    borderFocus: "focus:border-pink-500",
    ring: "focus:ring-pink-500",
    glow: "from-pink-950/20",
    glowBlur: "bg-pink-500/15",
    primaryBtn: "bg-pink-600 hover:bg-pink-700 text-white",
  },
  cleric: {
    text: "text-amber-500",
    textMuted: "text-amber-400",
    bg: "bg-amber-500/10",
    bgActive: "bg-amber-500/20",
    border: "border-amber-500/30",
    borderFocus: "focus:border-amber-500",
    ring: "focus:ring-amber-500",
    glow: "from-amber-950/20",
    glowBlur: "bg-amber-500/15",
    primaryBtn: "bg-amber-600 hover:bg-amber-700 text-white",
  },
  druid: {
    text: "text-emerald-500",
    textMuted: "text-emerald-400",
    bg: "bg-emerald-500/10",
    bgActive: "bg-emerald-500/20",
    border: "border-emerald-500/30",
    borderFocus: "focus:border-emerald-500",
    ring: "focus:ring-emerald-500",
    glow: "from-emerald-950/20",
    glowBlur: "bg-emerald-500/15",
    primaryBtn: "bg-emerald-600 hover:bg-emerald-700 text-white",
  },
  fighter: {
    text: "text-rose-500",
    textMuted: "text-rose-400",
    bg: "bg-rose-500/10",
    bgActive: "bg-rose-500/20",
    border: "border-rose-500/30",
    borderFocus: "focus:border-rose-500",
    ring: "focus:ring-rose-500",
    glow: "from-rose-950/20",
    glowBlur: "bg-rose-500/15",
    primaryBtn: "bg-rose-600 hover:bg-rose-700 text-white",
  },
  monk: {
    text: "text-sky-500",
    textMuted: "text-sky-400",
    bg: "bg-sky-500/10",
    bgActive: "bg-sky-500/20",
    border: "border-sky-500/30",
    borderFocus: "focus:border-sky-500",
    ring: "focus:ring-sky-500",
    glow: "from-sky-950/20",
    glowBlur: "bg-sky-500/15",
    primaryBtn: "bg-sky-600 hover:bg-sky-700 text-white",
  },
  paladin: {
    text: "text-yellow-500",
    textMuted: "text-yellow-400",
    bg: "bg-yellow-500/10",
    bgActive: "bg-yellow-500/20",
    border: "border-yellow-500/30",
    borderFocus: "focus:border-yellow-500",
    ring: "focus:ring-yellow-500",
    glow: "from-yellow-950/20",
    glowBlur: "bg-yellow-500/15",
    primaryBtn: "bg-yellow-600 hover:bg-yellow-700 text-white",
  },
  ranger: {
    text: "text-green-500",
    textMuted: "text-green-400",
    bg: "bg-green-500/10",
    bgActive: "bg-green-500/20",
    border: "border-green-500/30",
    borderFocus: "focus:border-green-500",
    ring: "focus:ring-green-500",
    glow: "from-green-950/20",
    glowBlur: "bg-green-500/15",
    primaryBtn: "bg-green-600 hover:bg-green-700 text-white",
  },
  rogue: {
    text: "text-slate-400",
    textMuted: "text-slate-500",
    bg: "bg-slate-500/10",
    bgActive: "bg-slate-500/20",
    border: "border-slate-500/30",
    borderFocus: "focus:border-slate-500",
    ring: "focus:ring-slate-500",
    glow: "from-slate-950/20",
    glowBlur: "bg-slate-500/15",
    primaryBtn: "bg-slate-600 hover:bg-slate-700 text-white",
  },
  sorcerer: {
    text: "text-orange-500",
    textMuted: "text-orange-400",
    bg: "bg-orange-500/10",
    bgActive: "bg-orange-500/20",
    border: "border-orange-500/30",
    borderFocus: "focus:border-orange-500",
    ring: "focus:ring-orange-500",
    glow: "from-orange-950/20",
    glowBlur: "bg-orange-500/15",
    primaryBtn: "bg-orange-600 hover:bg-orange-700 text-white",
  },
  warlock: {
    text: "text-teal-500",
    textMuted: "text-teal-400",
    bg: "bg-teal-500/10",
    bgActive: "bg-teal-500/20",
    border: "border-teal-500/30",
    borderFocus: "focus:border-teal-500",
    ring: "focus:ring-teal-500",
    glow: "from-teal-950/20",
    glowBlur: "bg-teal-500/15",
    primaryBtn: "bg-teal-600 hover:bg-teal-700 text-white",
  },
  wizard: {
    text: "text-violet-500",
    textMuted: "text-violet-400",
    bg: "bg-violet-500/10",
    bgActive: "bg-violet-500/20",
    border: "border-violet-500/30",
    borderFocus: "focus:border-violet-500",
    ring: "focus:ring-violet-500",
    glow: "from-violet-950/20",
    glowBlur: "bg-violet-500/15",
    primaryBtn: "bg-violet-600 hover:bg-violet-700 text-white",
  },
  artificer: {
    text: "text-cyan-500",
    textMuted: "text-cyan-400",
    bg: "bg-cyan-500/10",
    bgActive: "bg-cyan-500/20",
    border: "border-cyan-500/30",
    borderFocus: "focus:border-cyan-500",
    ring: "focus:ring-cyan-500",
    glow: "from-cyan-950/20",
    glowBlur: "bg-cyan-500/15",
    primaryBtn: "bg-cyan-600 hover:bg-cyan-700 text-white",
  },
};

export const DEFAULT_THEME: ClassTheme = {
  text: "text-emerald-500",
  textMuted: "text-emerald-400",
  bg: "bg-emerald-500/10",
  bgActive: "bg-emerald-500/20",
  border: "border-emerald-500/30",
  borderFocus: "focus:border-emerald-500",
  ring: "focus:ring-emerald-500",
  glow: "from-emerald-950/20",
  glowBlur: "bg-emerald-500/15",
  primaryBtn: "bg-emerald-600 hover:bg-emerald-700 text-white",
};
