export const SOURCE_LABELS: Record<string, string> = {
  AAG: "Astral Adventurer's Guide",
  AI: "Acquisitions Incorporated",
  BAM: "Boo's Astral Menagerie",
  BGG: "Bigby Presents: Glory of the Giants",
  BMT: "The Book of Many Things",
  XPHB: "Player's Handbook",
  XDMG: "Dungeon Master's Guide",
  XMM: "Monster Manual",
  FTD: "Fizban's Treasury of Dragons",
  TCE: "Tasha's Cauldron of Everything",
  XGE: "Xanathar's Guide to Everything",
  EFA: "Eberron: Forge of the Artificer",
  ERLW: "Eberron: Rising from the Last War",
  EGW: "Explorer's Guide to Wildemount",
  GGR: "Guildmasters' Guide to Ravnica",
  MOT: "Mythic Odysseys of Theros",
  MPMM: "Mordenkainen Presents: Monsters of the Multiverse",
  MTF: "Mordenkainen's Tome of Foes",
  MPP: "Morte's Planar Parade",
  FRAIF: "Forgotten Realms: Adventures in Faerun",
  FRHOF: "Forgotten Realms: Heroes of Faerun",
  RHW: "Ravenloft: The Horrors Within",
  SATO: "Sigil and the Outlands",
  SCAG: "Sword Coast Adventurer's Guide",
  SCC: "Strixhaven: A Curriculum of Chaos",
  VGM: "Volo's Guide to Monsters",
  VRGR: "Van Richten's Guide to Ravenloft",
};

export const ABILITIES = ["STR", "DEX", "CON", "INT", "WIS", "CHA"];
export const ABILITY_NAMES: Record<string, string> = {
  STR: "Strength",
  DEX: "Dexterity",
  CON: "Constitution",
  INT: "Intelligence",
  WIS: "Wisdom",
  CHA: "Charisma",
};

export const SKILL_OPTIONS = [
  "Acrobatics",
  "Animal Handling",
  "Arcana",
  "Athletics",
  "Deception",
  "History",
  "Insight",
  "Intimidation",
  "Investigation",
  "Medicine",
  "Nature",
  "Perception",
  "Performance",
  "Persuasion",
  "Religion",
  "Sleight of Hand",
  "Stealth",
  "Survival",
];

export const TOOL_OPTIONS = [
  "Alchemist's Supplies",
  "Brewer's Supplies",
  "Calligrapher's Supplies",
  "Carpenter's Tools",
  "Cartographer's Tools",
  "Cobbler's Tools",
  "Cook's Utensils",
  "Glassblower's Tools",
  "Jeweler's Tools",
  "Leatherworker's Tools",
  "Mason's Tools",
  "Painter's Supplies",
  "Potter's Tools",
  "Smith's Tools",
  "Thieves' Tools",
  "Tinker's Tools",
  "Weaver's Tools",
  "Woodcarver's Tools",
  "Disguise Kit",
  "Forgery Kit",
  "Herbalism Kit",
  "Navigator's Tools",
  "Poisoner's Kit",
];

export const FIGHTING_STYLE_OPTIONS = [
  "Archery",
  "Blind Fighting",
  "Defense",
  "Dueling",
  "Great Weapon Fighting",
  "Interception",
  "Protection",
  "Thrown Weapon Fighting",
  "Two-Weapon Fighting",
  "Unarmed Fighting",
];

export const WEAPON_MASTERY_OPTIONS = [
  "Battleaxe",
  "Club",
  "Dagger",
  "Dart",
  "Flail",
  "Glaive",
  "Greataxe",
  "Greatclub",
  "Greatsword",
  "Halberd",
  "Handaxe",
  "Javelin",
  "Lance",
  "Light Hammer",
  "Longbow",
  "Longsword",
  "Mace",
  "Maul",
  "Morningstar",
  "Pike",
  "Quarterstaff",
  "Rapier",
  "Scimitar",
  "Shortbow",
  "Shortsword",
  "Sickle",
  "Sling",
  "Spear",
  "Trident",
  "Warhammer",
  "Whip",
];

export const PREPARED_SPELLS_BY_CLASS: Record<string, number[]> = {
  artificer: [2, 3, 4, 5, 6, 6, 7, 7, 9, 10, 10, 11, 11, 12, 13, 13, 14, 14, 15, 15],
  bard: [4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 15, 16, 16, 17, 18, 18, 19, 20, 22, 22],
  cleric: [4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 15, 16, 16, 17, 18, 18, 19, 20, 22, 22],
  druid: [4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 15, 16, 16, 17, 18, 18, 19, 20, 22, 22],
  paladin: [0, 2, 3, 3, 5, 6, 6, 7, 7, 9, 10, 10, 11, 11, 12, 13, 13, 14, 14, 15],
  ranger: [0, 2, 3, 3, 5, 6, 6, 7, 7, 9, 10, 10, 11, 11, 12, 13, 13, 14, 14, 15],
  sorcerer: [4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 15, 16, 16, 17, 18, 18, 19, 20, 22, 22],
  warlock: [2, 3, 4, 5, 6, 7, 7, 8, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 15, 15],
  wizard: [4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 15, 16, 16, 17, 18, 18, 19, 20, 22, 22],
};

export const INVOCATION_LEVEL_PREREQUISITES: Record<string, number> = {
  "Ascendant Step": 5,
  "Devouring Blade": 12,
  Lifedrinker: 9,
  "Master of Myriad Forms": 5,
  "One with Shadows": 5,
  "Otherworldly Leap": 2,
  "Thirsting Blade": 5,
  "Visions of Distant Realms": 9,
  "Whispers of the Grave": 7,
  "Witch Sight": 15,
};

export const INVOCATION_PACT_PREREQUISITES: Record<string, string> = {
  "Devouring Blade": "Pact of the Blade",
  "Eldritch Smite": "Pact of the Blade",
  "Gift of the Protectors": "Pact of the Tome",
  "Investment of the Chain Master": "Pact of the Chain",
  Lifedrinker: "Pact of the Blade",
  "Thirsting Blade": "Pact of the Blade",
};

export const WARLOCK_INVOCATION_COUNTS = [
  1, 3, 3, 3, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 10, 10,
];

export const DRAGON_DAMAGE_BY_ANCESTRY: Record<string, string> = {
  Black: "Acid",
  Blue: "Lightning",
  Brass: "Fire",
  Bronze: "Lightning",
  Copper: "Acid",
  Gold: "Fire",
  Green: "Poison",
  Red: "Fire",
  Silver: "Cold",
  White: "Cold",
  Amethyst: "Force",
  Crystal: "Radiant",
  Emerald: "Psychic",
  Sapphire: "Thunder",
  Topaz: "Necrotic",
};
