import { createFileRoute } from "@tanstack/react-router";
import type { ForgeData } from "@/lib/forge/forge-data";
import {
  getBackgroundsFromDb,
  getActiveEffectsFromDb,
  getClassFeaturesFromDb,
  getClassSpellsFromDb,
  getBuilderInitialCharacterFromDb,
  getClassesFromDb,
  getFeatureActiveEffectsFromDb,
  getFeatsFromDb,
  getLanguagesFromDb,
  getSpeciesFromDb,
  getSpellsFromDb,
  getSubclassesFromDb,
  getItemActiveEffectsFromDb,
  getSpellActiveEffectsFromDb,
  getMagicItemsFromDb,
  getSpeciesVariantsFromDb,
  getWeaponsFromDb,
  getArmorFromDb,
  getChallengeRatingsFromDb,
  getCharOptionsFromDb,
  getConditionsFromDb,
  getCreatureBuilderEntriesFromDb,
  getItemCardReferencesFromDb,
  getItemGroupsFromDb,
  getItemPropertiesFromDb,
  getItemTypeAdditionalEntriesFromDb,
  getItemTypesFromDb,
  getMagicVariantsFromDb,
  getMundaneGearFromDb,
  getOptionalFeaturesFromDb,
  getRulesActionsFromDb,
  getSensesFromDb,
  getSkillsFromDb,
  getWeaponMasteriesFromDb,
} from "@/lib/db-functions";

import { z } from "zod";

const builderSearchSchema = z.object({
  id: z.number().optional(),
});

export const Route = createFileRoute("/builder")({
  validateSearch: (search) => builderSearchSchema.parse(search),
  loader: async ({ search }): Promise<ForgeData & { initialCharacter?: any }> => {
    const [
      classes,
      species,
      speciesVariants,
      subclasses,
      backgrounds,
      feats,
      spells,
      classSpells,
      classFeatures,
      languages,
      activeEffects,
      featureActiveEffects,
      itemActiveEffects,
      spellActiveEffects,
      magicItems,
      weapons,
      armor,
      skills,
      senses,
      conditions,
      rulesActions,
      optionalFeatures,
      charOptions,
      mundaneGear,
      weaponMasteries,
      itemProperties,
      itemTypes,
      itemTypeAdditionalEntries,
      itemGroups,
      magicVariants,
      itemCardReferences,
      challengeRatings,
      creatureBuilderEntries,
    ] = await Promise.all([
      getClassesFromDb(),
      getSpeciesFromDb(),
      getSpeciesVariantsFromDb(),
      getSubclassesFromDb(),
      getBackgroundsFromDb(),
      getFeatsFromDb(),
      getSpellsFromDb(),
      getClassSpellsFromDb(),
      getClassFeaturesFromDb(),
      getLanguagesFromDb(),
      getActiveEffectsFromDb(),
      getFeatureActiveEffectsFromDb(),
      getItemActiveEffectsFromDb(),
      getSpellActiveEffectsFromDb(),
      getMagicItemsFromDb(),
      getWeaponsFromDb(),
      getArmorFromDb(),
      getSkillsFromDb(),
      getSensesFromDb(),
      getConditionsFromDb(),
      getRulesActionsFromDb(),
      getOptionalFeaturesFromDb(),
      getCharOptionsFromDb(),
      getMundaneGearFromDb(),
      getWeaponMasteriesFromDb(),
      getItemPropertiesFromDb(),
      getItemTypesFromDb(),
      getItemTypeAdditionalEntriesFromDb(),
      getItemGroupsFromDb(),
      getMagicVariantsFromDb(),
      getItemCardReferencesFromDb(),
      getChallengeRatingsFromDb(),
      getCreatureBuilderEntriesFromDb(),
    ]);

    const initialCharacter = search.id
      ? await getBuilderInitialCharacterFromDb({ data: { id: search.id } })
      : null;

    return {
      classes,
      species,
      speciesVariants,
      subclasses,
      backgrounds,
      feats,
      spells,
      classSpells,
      classFeatures,
      languages,
      activeEffects,
      featureActiveEffects,
      itemActiveEffects,
      spellActiveEffects,
      magicItems,
      weapons,
      armor,
      skills,
      senses,
      conditions,
      rulesActions,
      optionalFeatures,
      charOptions,
      mundaneGear,
      weaponMasteries,
      itemProperties,
      itemTypes,
      itemTypeAdditionalEntries,
      itemGroups,
      magicVariants,
      itemCardReferences,
      challengeRatings,
      creatureBuilderEntries,
      initialCharacter,
    };
  },
});
