export const SOURCES = {
  core: ["XPHB", "XMM", "XDMG", "PHB", "MM", "DMG"],
  supplements: ["TCE", "XGE", "FTD", "BGG", "BMT", "MPMM", "VGM", "MTF", "AI", "RHW"],
  settings: [
    "FRAiF",
    "FRHoF",
    "EFA",
    "ERLW",
    "GGR",
    "EGW",
    "MOT",
    "VRGR",
    "SCC",
    "SCAG",
    "AAG",
    "BAM",
    "MPP",
    "SatO",
  ],
} as const;

export type SourceTier = keyof typeof SOURCES;

export const BLOCKED_SOURCES: string[] = [
  "HB",
  "HOMEBREW",
  "UA",
  "UAA",
  "UAB",
  "UACFV",
  "UACFV2",
  "UACFV3",
  "UACFV4",
  "UACFV5",
  "UACFV6",
  "UACFV7",
  "UACFV8",
  "UACFV9",
  "UACFV10",
  "UACFV11",
  "UAE",
  "UAEAG",
  "UAF",
  "UAFPP",
  "UAM",
  "UAR",
  "UAS",
  "UATMC",
  "UATRR",
  "UAWGE",
  "UA2020PsionicOptionsRevisited",
  "UA2020SubclassesPt1",
  "UA2020SubclassesPt2",
  "UA2020SubclassesPt3",
  "UA2020SubclassesPt4",
  "UA2020SubclassesPt5",
  "UA2020SpellsAndMagicTattoos",
  "UA2020Feats",
  "UA2021DraconicOptions",
  "UA2021FolkOfTheFeywild",
  "UA2021MagesOfStrixhaven",
  "UA2021TravelersOfTheMultiverse",
  "UA2022HeroesOfKrynn",
  "UA2022HeroesOfKrynnRevisited",
  "UA2022GiantOptions",
  "UA2022WondersOfTheMultiverse",
  "UA2022CharacterOrigins",
  "UA2022ExpertClasses",
  "UA2022ClericAndRevisedSpecies",
  "UA2023DruidAndPaladin",
  "UA2023PlayerHandbookCb1",
  "UA2023PlayerHandbookCb2",
  "UA2023PlayerHandbookCb3",
  "UA2023PlayerHandbookCb4",
  "PSA",
  "PSD",
  "PSI",
  "PSK",
  "PSX",
  "PSZ",
  "UATHEMYSTICCLASS",
];
