/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompendiumRouteImport } from './routes/compendium'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharacterIdRouteImport } from './routes/character.$id'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as ApiPartyRouteImport } from './routes/api/party'
import { Route as ApiNotionRouteImport } from './routes/api/notion'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompendiumRoute = CompendiumRouteImport.update({
  id: '/compendium',
  path: '/compendium',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/compendium.lazy').then((d) => d.Route))
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/builder.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterIdRoute = CharacterIdRouteImport.update({
  id: '/character/$id',
  path: '/character/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPartyRoute = ApiPartyRouteImport.update({
  id: '/api/party',
  path: '/api/party',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotionRoute = ApiNotionRouteImport.update({
  id: '/api/notion',
  path: '/api/notion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/compendium': typeof CompendiumRoute
  '/login': typeof LoginRoute
  '/api/notion': typeof ApiNotionRoute
  '/api/party': typeof ApiPartyRoute
  '/api/sync': typeof ApiSyncRoute
  '/character/$id': typeof CharacterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/compendium': typeof CompendiumRoute
  '/login': typeof LoginRoute
  '/api/notion': typeof ApiNotionRoute
  '/api/party': typeof ApiPartyRoute
  '/api/sync': typeof ApiSyncRoute
  '/character/$id': typeof CharacterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/compendium': typeof CompendiumRoute
  '/login': typeof LoginRoute
  '/api/notion': typeof ApiNotionRoute
  '/api/party': typeof ApiPartyRoute
  '/api/sync': typeof ApiSyncRoute
  '/character/$id': typeof CharacterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/compendium'
    | '/login'
    | '/api/notion'
    | '/api/party'
    | '/api/sync'
    | '/character/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/compendium'
    | '/login'
    | '/api/notion'
    | '/api/party'
    | '/api/sync'
    | '/character/$id'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/compendium'
    | '/login'
    | '/api/notion'
    | '/api/party'
    | '/api/sync'
    | '/character/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  CompendiumRoute: typeof CompendiumRoute
  LoginRoute: typeof LoginRoute
  ApiNotionRoute: typeof ApiNotionRoute
  ApiPartyRoute: typeof ApiPartyRoute
  ApiSyncRoute: typeof ApiSyncRoute
  CharacterIdRoute: typeof CharacterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compendium': {
      id: '/compendium'
      path: '/compendium'
      fullPath: '/compendium'
      preLoaderRoute: typeof CompendiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/$id': {
      id: '/character/$id'
      path: '/character/$id'
      fullPath: '/character/$id'
      preLoaderRoute: typeof CharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/party': {
      id: '/api/party'
      path: '/api/party'
      fullPath: '/api/party'
      preLoaderRoute: typeof ApiPartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notion': {
      id: '/api/notion'
      path: '/api/notion'
      fullPath: '/api/notion'
      preLoaderRoute: typeof ApiNotionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  CompendiumRoute: CompendiumRoute,
  LoginRoute: LoginRoute,
  ApiNotionRoute: ApiNotionRoute,
  ApiPartyRoute: ApiPartyRoute,
  ApiSyncRoute: ApiSyncRoute,
  CharacterIdRoute: CharacterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
